### ISSUE TITLE
Would like to help you with the project!

### ISSUE THREAD

**Issue by pappricot** [cdmoro/covid-19-stats#2]
Hi there! Thank you so much for creating such a good visual piece of info! I'd like to help you. I've cloned your repo and added few languages in locale file, but I don't have permission to push to a remote branch for you to see.

Anya aka Pappricot

**Comment by cdmoro** [comment]
Hello! First of all, thanks for thr contributivo! I really appreciate that.
About the changes, I think you should make a pull request. You have to fork this repo, make the changes, commit them (on your forked repo) and come back to the pull request section so I can see it and merge.
https://help.github.com/en/enterprise/2.16/user/github/collaborating-with-issues-and-pull-requests/creating-a-pull-request-from-a-fork

See you!

**Comment by pappricot** [comment]
Thank you for the link! I haven't done open-source projects on github :P following the steps now will send pull request soon!
